### ISSUE TITLE
Retrieve Customer Card Details

### ISSUE THREAD

**Issue by digitalgym** [prajapatichintan/Zoho#1]
I'm looking for a way to read a customer's current card details, to display the last 4 digits and card brand is this possible?

**Comment by prajapatichintan** [comment]
You can retrieve customer card details from subscription object itself. 
check below screenshot which shows the property which returns the last four digit of card. 
![image](https://user-images.githubusercontent.com/5564408/67463690-82e6ca80-f65f-11e9-8a61-89d2edc76d3c.png)


https://github.com/prajapatichintan/Zoho-Subscriptions-API-wrapper/blob/master/ZohoSubscription/SubscriptionApi.cs

You need to retrieve Subscription Using Get Method. and within response you should get values from card.last_four_digits 

let me know if that doesn't work. You may send me the example code which you are trying.
